### PR TITLE
 Pbi books page

### PR DESCRIPTION
**Pull request by swapnilp0x00**
- books page
- books resolver
- specs

### CODE REVIEW

**Comment by bherr2** [comment]
Looks pretty good to me. I notice it's marked as Draft still. Let me know when you're ready for merging. I CC @lecross so he can do a spot check himself on the build preview here: https://60a2dcec07f9bd36af4e45b7--scimaps.netlify.app

**Comment by lecross** [comment]
Things to fix:
- H2 age header, Books, is missing. Color: #757575. Size: 40px.
- H3 headers are not blue, they are #757575. Size: 32px.
- The page content should not span the page. Page content is contained in centered container that is 1248px wide.
- There is no gray background color. Background is white.
- The carousels are only 400px as shown. Default should be closer to 600px as you have an equal two column spread. 
- The carousel dot should not be blue, but green (#8DC63F).
- The Book Exceprt (PDF) button should go to a PDF, not to Amazon. The PDFs don't yet exist. For now, remove the buttons from displaying.


Other Notes:
- The main navigation hover/active background has border-radius. That should be zero.
- Do you not have the logo? Thought I provided that. Please confirm.
- The page footer is missing information. The phone number: 812-855-9930. Use this in the footer and the Contact Us section. For the email use: cnscntr@indiana.edu
- In the footer, for location, I'm not sure how you are implementing but the link is https://goo.gl/maps/yFFVMmMRzBNYU1pq8 and the coordinates are 39.17294975111009, -86.52330522995477

There is some work left to do on the About page. I will fix the Katy image issue. That section needs to display both curator and co-curators, there are three people.

**Comment by lecross** [comment]
One other item. The carousels should loop.

**Review by lecross — CHANGES_REQUESTED** [review]
Page width remains off. Max width is 1280px for content, broken down into 1248px for content with matching 16px gutters on the left and right (1248+32=1280). There needs to be 48px between the logo/nav bar and the header BOOKS. The carousels are not sized correctly. Content is spilling out. At a column width of 600px, which is what there should be, the image would be 600x338px. Currently the sci-carousel-item width is set to 1095px and the height to some rem height that equals 400px. The raw carousel images are 960x540px, which will give you 600x338 when the image is dropped into a 600px width space. The MIT Press text below author should be a link. URL (http://mitpress.mit.edu/). The assets for the PDF download don't exist yet. That is a battle I have to fight.

**Review by lecross — CHANGES_REQUESTED** [review]
Carousels look much better. Do not have them auto-slide though. All text links should be colored the same as the green as the bullets under the carousel: #8DC63F. Text links do not have a text-decoration of underline until hover. In the black Footer bar use the following: "Acknowledgements: This exhibit is supported by the National Science Foundation under Grant No. IIS-0238261, CHE-0524661, IIS-0534909 and IIS-0715303, the James S. McDonnell Foundation; Thomson Reuters; the Cyberinfrastructure for Network Science Center, University Information Technology Services, and the School of Library and Information Science, all three at Indiana University. Some of the data used to generate the science maps is from the Web of Science by Thomson Reuters and Scopus by Elsevier. Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation." The Footer should only be 48px tall, not 72px. Hover state for the SM icons is to go from #ffffff to #7997a3 on a white background that is 48x48.

**Review by lecross — CHANGES_REQUESTED** [review]
The icons in the footer are too large. Remove the font-size on mat-icon for these icons. Not sure about the implications, but fixes the oversized icons. There seems to be an issue with the flexbox as well. The item exceeds the confines of the container. Outside of that things look good.

**Comment by swapnilp0x00** [comment]
Removing font size was making oversized icons very small compared to others, so I reduced it to 2rem.

**Review by lecross — APPROVED** [review]
The Book page looks good. Some general things were solved that relate to Footer and Logo Bar as well.

**Review by bherr2 — APPROVED** [review]
Merging!

**Pull request merged**
