### PR TITLE
Pbi 13 carousel

### PR DESCRIPTION
**Pull request by edlu77**
#13

### CODE REVIEW

**Comment by bherr2** [comment]
Why the bajillion changes on files again? Please pay attention when committing. You'll need to remove most of the files staged for merging before this can ever be accepted.

**Comment by bherr2** [comment]
> Why the bajillion changes on files again? Please pay attention when committing. You'll need to remove most of the files staged for merging before this can ever be accepted.

New changes seem to have resolved this

**Review by axdanbol — CHANGES_REQUESTED** [review]
All travis jobs are failing! Again with the useless changes to multiple files (.gitignore, README.md, package-lock.json <= needs regeneration). Missing tests. Missing theming. Carousel files needs to  be moved to `shared/components`. All these things needs fixing before a proper review can be made.

**Review by bherr2 — COMMENTED** [review]
> All travis jobs are failing! Again with the useless changes to multiple files (.gitignore, README.md, package-lock.json <= needs regeneration). Missing tests. Missing theming. Carousel files needs to be moved to `shared/components`. All these things needs fixing before a proper review can be made.

One thing about the .gitignore and README.md, those were generated by github and I believe had \r\n instead of \n so probably ok. Before it was basically every file was changed due to line endings.

**Pull request merged**
